#!/bin/bash

REMOTE_USER="$1"
REMOTE_IP="$2"
REMOTE_OUTPUT_FILE="$3"

TEMP_FILE="/tmp/power_consumption"
SSH_OPTS=' -o StrictHostKeyChecking=no -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o LogLevel=quiet '

function stop {
	sync

	# Send results to the remote host
	scp $SSH_OPTS $TEMP_FILE $REMOTE_USER@$REMOTE_IP:~/$REMOTE_OUTPUT_FILE >/dev/null

	exit 0
}
trap stop SIGTERM SIGINT SIGKILL

function get_power_consumption {
	echo -e "`date +%s`\t`ipmitool sdr get Power | grep Reading | cut -d':' -f 2 | awk '{print $1;}'`" >> $TEMP_FILE
}

echo -n > $TEMP_FILE
while [ true ]; do
	get_power_consumption
	sleep 1
done
