#!/bin/bash

# Get variables from config file
. ./config

# Load required modules
modprobe ipmi_si
modprobe ipmi_devintf

# Use ipmitool to activate BMC network access and create a new user
ipmitool lan set 1 ipaddr `host $(hostname -s)-bmc | awk '{print $4;}'` > /dev/null 2>&1
ipmitool lan set 1 netmask `ifconfig | grep ^br0 -A1 | tail -1 | awk '{print $4;}' | cut -d':' -f 2` > /dev/null 2>&1
ipmitool lan set 1 auth ADMIN MD5 > /dev/null 2>&1
ipmitool lan set 1 access on > /dev/null 2>&1
ipmitool user set name 3 $BMC_USER > /dev/null 2>&1
ipmitool user set password 3 $BMC_MDP > /dev/null 2>&1
ipmitool channel setaccess 1 3 link=on ipmi=on callin=on privilege=4 > /dev/null 2>&1
ipmitool user enable 3 > /dev/null 2>&1
