#!/bin/bash

VM_BACKING_IMG_DIR="$1"
RESULTS_DIR="$2"

APACHE_LOGFILE="/mnt/var/log/apache2/access.log"
SSH_OPTS=' -o StrictHostKeyChecking=no -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o LogLevel=quiet '

mkdir $RESULTS_DIR 2>/dev/null

for VM in `ls -1 $VM_BACKING_IMG_DIR/ | grep vm`; do

	VM_NAME=$(echo $VM | cut -d'.' -f1)

	echo -ne "Get results of $VM_NAME workload.."

	# Mount image
	qemu-nbd --connect=/dev/nbd0 $VM_BACKING_IMG_DIR/$VM
	sleep 5
	mount /dev/nbd0p1 /mnt

	# Get stats
	cp /mnt/tmp/stats $RESULTS_DIR/$VM_NAME.stats

	# Get start and stop times
	if [ -e $APACHE_LOGFILE.1 ]; then
		START_TIME=`head -1 $APACHE_LOGFILE.1 | cut -d' ' -f1`
	else
		START_TIME=`head -1 $APACHE_LOGFILE | cut -d' ' -f1`
	fi
	if [ -s $APACHE_LOGFILE ]; then
		END_TIME=`tail -1 $APACHE_LOGFILE | cut -d' ' -f1`
	else
		if [ -e $APACHE_LOGFILE.1 ]; then
			END_TIME=`tail -1 $APACHE_LOGFILE.1 | cut -d' ' -f1`
		else
			END_TIME=`tail -1 $APACHE_LOGFILE | cut -d' ' -f1`
		fi
	fi

	TIME="$START_TIME"

	# Clean results file
	echo -n > $RESULTS_DIR/$VM_NAME

	# Get the requests rate per second
	while [ $TIME -le $END_TIME ]; do
		if [ -e $APACHE_LOGFILE.1 ]; then
			echo -e "$TIME,$(cat $APACHE_LOGFILE $APACHE_LOGFILE.1 | grep $TIME | wc -l)" >> $RESULTS_DIR/$VM_NAME
		else
			echo -e "$TIME,$(cat $APACHE_LOGFILE | grep $TIME | wc -l)" >> $RESULTS_DIR/$VM_NAME
		fi
		TIME=$(($TIME + 1))
	done

	sync
	umount /mnt
	qemu-nbd -d /dev/nbd0 >/dev/null

	echo -e ". DONE"
done
