#!/bin/bash

VIDEO_SRC="$1"
REMOTE_USER="$2"
REMOTE_IP="$3"
REMOTE_OUTPUT_FILE="$4"
SSH_OPTS=' -o StrictHostKeyChecking=no -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o LogLevel=quiet '


# Start encoding
HandBrakeCLI -i $VIDEO_SRC -o /dev/zero > /tmp/encoding_flow 2>/dev/null &
PID=$!

echo -e "$(date +%s)\tSTART" > /tmp/results

# Wait for encoding initialization
sleep 10

# Capture the fps rate every seconds
while ps -p $PID > /dev/null; do
	echo -e "$(date +%s)\t$(cat -v /tmp/encoding_flow | sed -e 's/M/\n/g' | tail -2 | head -1 | cut -d' ' -f8 | tail -c +2)" >> /tmp/results
	sleep 1
done

wait
sync

echo -e "$(date +%s)\tEND" >> /tmp/results

# Send results to the remote host
sync
scp $SSH_OPTS /tmp/results $REMOTE_USER@$REMOTE_IP:~/$REMOTE_OUTPUT_FILE >/dev/null

