#!/bin/bash

NODE="$1"

if [ -n "$NODE" ]; then

	if [ -f "$NODE" ]; then
		echo -e "Powering off $((cat $NODE | wc -l)) nodes ..."
		kapower3 --off -f $NODE >/dev/null
	else
		echo -e "Powering off node '$NODE' ..."
		kapower3 --off -m $NODE >/dev/null
	fi
fi
