#!/bin/bash

NODE="$1"
BMC_USER="$2"
BMC_MDP="$3"

function wait_for_boot {
	local NODE="$1"

	while ! ping -c 1 $NODE > /dev/null; do
		sleep 2
	done

	# Wait 30 more seconds (start services)
	sleep 30
}


if [ -n "$NODE" ]; then

	START=$(date +%s)

	if [ -f "$NODE" ]; then

		# Boot nodes list
		echo -en "Booting $(cat $NODE|wc -l) nodes .."
		
		if [ -n "$BMC_USER" -a -n "$BMC_MDP" ]; then
			# Using IPMI
			for N in `cat $NODE`; do
				ipmitool -H $(host $(echo "$N" | cut -d'.' -f1)-bmc.$(echo "$N" | cut -d'.' -f2,3,4) | awk '{print $4;}') -I lan -U $BMC_USER -P $BMC_MDP chassis power on > /dev/null
			done
		else
			# Using kapower
			kapower3 --on -f $NODE >/dev/null
		fi

		# Wait for boot of all nodes
		for N in `cat $NODE`; do
			wait_for_boot $N &
		done
		wait

		END=$(date +%s)

		echo -e ". done. (total boot time = $(($END - $START)))s"
		
	else
		# Boot node
		echo -en "Booting node '$NODE' .."

		if [ -n "$BMC_USER" -a -n "$BMC_MDP" ]; then
			# Using IPMI
			ipmitool -H $(host $(echo "$NODE" | cut -d'.' -f1)-bmc.$(echo "$NODE" | cut -d'.' -f2,3,4) | awk '{print $4;}') -I lan -U $BMC_USER -P $BMC_MDP chassis power on > /dev/null
		else
			# Using kapower
			kapower3 --on -m $NODE >/dev/null
		fi

		# Wait for boot
		wait_for_boot $NODE

		END=$(date +%s)

		echo -e ". done. (boot time = $(($END - $START)))s"
	fi
fi
