#!/usr/bin/env python
from sys import *
import httplib
import re

# Default port
port = 54398

# Script to send a notification token to rWait


if len(argv) < 3 or argv[0] in ["-h", "--help"]:
    print("rNotify url token")
    exit(1)

if re.search(":", argv[1]) != None:
    host,port = argv[1].split(":")
    port = int(port)
else:
    host = argv[1]

token = argv[2]

# Send the url
try:
    conn = httplib.HTTPConnection(host, port)
    conn.request("POST", "/" + token)
    res = conn.getresponse()
    if res.status != 200:
        stderr.write(res.reason + "\n")
        exit(1)	
except Exception as err:
    stderr.write(str(err) + "\n")
    exit(1)

exit(0)
