#!/usr/bin/env python
from sys import *
import httplib

#Script to send a notification token to rWait

if len(argv) < 3 or argv[0] in ["-h", "--help"]:
	print("rNotify url token")
	exit(1)

url = argv[1]
token = argv[2]

#send the url
try:
	conn = httplib.HTTPConnection(url)
	conn.request("POST", "/" + token)
	res = conn.getresponse()
	if res.status != 200:
		stderr.write(res.reason + "\n")
		exit(1)	
except Exception as err:
	stderr.write(str(err) + "\n")
	exit(1)
exit(0)