#!/bin/bash

# Get parameters
NODE_LIST="$1"
VM_IMG="$2"
DEST_DIR="$3"

# Set global variables
SSH_USER='root'
SSH_OPTS=' -o StrictHostKeyChecking=no -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o LogLevel=quiet '


echo -ne "Sending VM base IMG to nodes .."

# Kaput method
#kaput -M $NODE_LIST $VM_IMG $DEST_DIR/

# SCP method
for NODE in `cat $NODE_LIST`; do
       # Send base IMG_VM to the node if it doesn't already exist
       if ( ssh $SSH_USER@$NODE $SSH_OPTS ''[ ! -e $DEST_DIR/$(basename $VM_IMG) ]'' ); then
               scp $SSH_OPTS $VM_IMG $SSH_USER@$NODE:$DEST_DIR/
       fi
done

echo -e ". DONE\n"
