#!/bin/bash

WORKLOAD_SCRIPT="$1"
SCRIPT_OPTIONS="$2"
RESULTS_DIR="$3"
VM_IP="$4"

# Source config file variables
. ./config

VM_NAME=$(cat $IPS_NAMES | grep $VM_IP | cut -f 1)
LOCAL_USER=$(whoami)
LOCAL_IP=$(ip a | grep inet | grep eth0 | awk '{print $2;}' | cut -d'/' -f1)


# Send script to the VM
scp $SSH_OPTS $WORKLOAD_SCRIPT $SSH_USER@$VM_IP: >/dev/null

# Start the remote task in background
ssh $SSH_OPTS $SSH_USER@$VM_IP "nohup ~$SSH_USER/$(basename $WORKLOAD_SCRIPT) $SCRIPT_OPTIONS $LOCAL_USER $LOCAL_IP $RESULTS_DIR/$VM_NAME >/dev/null 2>&1 &"

# Wait for the results (end of workload)
while [ ! -f $RESULTS_DIR/$VM_NAME ]; do
	sleep 2
done

echo -e " Workload terminated in VM $VM_NAME ($VM_IP)"
