#!/bin/bash 

OUTPUT="./bench_vm.csv"

VM="vm-1"
IP="10.144.0.1"
SRC="griffon-85"
DST="griffon-92"

OPTS=" --live --verbose --timeout 300 "
SSH_OPTS=' -o StrictHostKeyChecking=no -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o LogLevel=quiet '

echo "WORKLOAD;BANDWIDTH;DURATION" > $OUTPUT

function inject_workload {

	local BYTES="$1K"

	ssh root@$IP $SSH_OPTS "killall -9 stress; stress --vm 1000 --vm-bytes $BYTES 2>&1" &

	sleep 10 
}

#for WORKLOAD in {10,50,100,200}; do
	for BANDWIDTH in {100,200,300,400,500,600,700,800,900,1000}; do

		ssh $DST $SSH_OPTS "sudo /etc/init.d/libvirt-bin restart" >/dev/null
		inject_workload 10
		START=$(date +%s)
		./migrate.sh $VM $SRC $DST $BANDWIDTH $OPTS
		END=$(date +%s)
		echo "$WORKLOAD;$BANDWIDTH;$(($END - $START))" >> $OUTPUT
		sleep 2
		
		ssh $SRC $SSH_OPTS "sudo /etc/init.d/libvirt-bin restart" >/dev/null
		inject_workload 50
		START=$(date +%s)
		./migrate.sh $VM $DST $SRC $BANDWIDTH $OPTS
		END=$(date +%s)
		echo "$WORKLOAD;$BANDWIDTH;$(($END - $START))" >> $OUTPUT
		sleep 2

		ssh $DST $SSH_OPTS "sudo /etc/init.d/libvirt-bin restart" >/dev/null
		inject_workload 100
		START=$(date +%s)
		./migrate.sh $VM $SRC $DST $BANDWIDTH $OPTS
		END=$(date +%s)
		echo "$WORKLOAD;$BANDWIDTH;$(($END - $START))" >> $OUTPUT
		sleep 2
		
		ssh $SRC $SSH_OPTS "sudo /etc/init.d/libvirt-bin restart" >/dev/null
		inject_workload 200
		START=$(date +%s)
		./migrate.sh $VM $DST $SRC $BANDWIDTH $OPTS
		END=$(date +%s)
		echo "$WORKLOAD;$BANDWIDTH;$(($END - $START))" >> $OUTPUT
		sleep 2

	done
#done

