#!/bin/bash

. ./config

NODE="$1"
VM="$2"
WORKLOAD="$3"

SSH_USER="root"
SSH_OPTS=' -o StrictHostKeyChecking=no -o BatchMode=yes -o UserKnownHostsFile=/dev/null -o LogLevel=quiet '

if [ `echo "$VM" | grep vm | wc -l` -lt 1 ]; then
        VM=`ssh $SSH_USER@$NODE $SSH_OPTS "virsh list | grep vm | head -$VM | tail -1" | awk '{print $2;}'`
fi

IP=$(cat $IPS_NAMES | grep -P "$VM\t" | awk '{print $2;}')

ssh $SSH_USER@$IP $SSH_OPTS "stress $WORKLOAD" &
sleep 1
